package com.example.hitlogger.presentation.common.theme

import androidx.compose.ui.graphics.Color

// Lavender Light
internal val primaryLavenderLight = Color(0xFF65558F)
internal val onPrimaryLavenderLight = Color(0xFFFFFFFF)
internal val primaryContainerLavenderLight = Color(0xFFE9DDFF)
internal val onPrimaryContainerLavenderLight = Color(0xFF211047)
internal val secondaryLavenderLight = Color(0xFF625B70)
internal val onSecondaryLavenderLight = Color(0xFFFFFFFF)
internal val secondaryContainerLavenderLight = Color(0xFFE6DBFA)
internal val onSecondaryContainerLavenderLight = Color(0xFF1E192B)
internal val tertiaryLavenderLight = Color(0xFF7E5260)
internal val onTertiaryLavenderLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLavenderLight = Color(0xFFFFD9E3)
internal val onTertiaryContainerLavenderLight = Color(0xFF31101D)
internal val errorLavenderLight = Color(0xFFBA1A1A)
internal val onErrorLavenderLight = Color(0xFFFFFFFF)
internal val errorContainerLavenderLight = Color(0xFFFFDAD6)
internal val onErrorContainerLavenderLight = Color(0xFF410002)
internal val backgroundLavenderLight = Color(0xFFFDF7FF)
internal val onBackgroundLavenderLight = Color(0xFF1D1B20)
internal val surfaceLavenderLight = Color(0xFFFDF7FF)
internal val onSurfaceLavenderLight = Color(0xFF1D1B20)
internal val surfaceVariantLavenderLight = Color(0xFFE7E0EB)
internal val onSurfaceVariantLavenderLight = Color(0xFF49454E)
internal val outlineLavenderLight = Color(0xFF7A757F)
internal val outlineVariantLavenderLight = Color(0xFFCAC4CF)
internal val scrimLavenderLight = Color(0xFF000000)
internal val inverseSurfaceLavenderLight = Color(0xFF322F35)
internal val inverseOnSurfaceLavenderLight = Color(0xFFF5EFF7)
internal val inversePrimaryLavenderLight = Color(0xFFCFBDFE)
internal val surfaceDimLavenderLight = Color(0xFFDED8E0)
internal val surfaceBrightLavenderLight = Color(0xFFFDF7FF)
internal val surfaceContainerLowestLavenderLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLavenderLight = Color(0xFFF8F2FA)
internal val surfaceContainerLavenderLight = Color(0xFFF2ECF4)
internal val surfaceContainerHighLavenderLight = Color(0xFFECE6EE)
internal val surfaceContainerHighestLavenderLight = Color(0xFFE6E0E9)

// Lavender Dark
internal val primaryLavenderDark = Color(0xFFCFBDFE)
internal val onPrimaryLavenderDark = Color(0xFF36265D)
internal val primaryContainerLavenderDark = Color(0xFF4D3D75)
internal val onPrimaryContainerLavenderDark = Color(0xFFE9DDFF)
internal val secondaryLavenderDark = Color(0xFFCCC2DB)
internal val onSecondaryLavenderDark = Color(0xFF332D41)
internal val secondaryContainerLavenderDark = Color(0xFF4A4458)
internal val onSecondaryContainerLavenderDark = Color(0xFFE8DEF8)
internal val tertiaryLavenderDark = Color(0xFFEFB8C8)
internal val onTertiaryLavenderDark = Color(0xFF4A2532)
internal val tertiaryContainerLavenderDark = Color(0xFF633B48)
internal val onTertiaryContainerLavenderDark = Color(0xFFFFD9E3)
internal val errorLavenderDark = Color(0xFFFFB4AB)
internal val onErrorLavenderDark = Color(0xFF690005)
internal val errorContainerLavenderDark = Color(0xFF93000A)
internal val onErrorContainerLavenderDark = Color(0xFFFFDAD6)
internal val backgroundLavenderDark = Color(0xFF141218)
internal val onBackgroundLavenderDark = Color(0xFFE6E0E9)
internal val surfaceLavenderDark = Color(0xFF141218)
internal val onSurfaceLavenderDark = Color(0xFFE6E0E9)
internal val surfaceVariantLavenderDark = Color(0xFF49454E)
internal val onSurfaceVariantLavenderDark = Color(0xFFCAC4CF)
internal val outlineLavenderDark = Color(0xFF948F99)
internal val outlineVariantLavenderDark = Color(0xFF49454E)
internal val scrimLavenderDark = Color(0xFF000000)
internal val inverseSurfaceLavenderDark = Color(0xFFE6E0E9)
internal val inverseOnSurfaceLavenderDark = Color(0xFF322F35)
internal val inversePrimaryLavenderDark = Color(0xFF65558F)
internal val surfaceDimLavenderDark = Color(0xFF141218)
internal val surfaceBrightLavenderDark = Color(0xFF3B383E)
internal val surfaceContainerLowestLavenderDark = Color(0xFF0F0D13)
internal val surfaceContainerLowLavenderDark = Color(0xFF1D1B20)
internal val surfaceContainerLavenderDark = Color(0xFF211F24)
internal val surfaceContainerHighLavenderDark = Color(0xFF2B292F)
internal val surfaceContainerHighestLavenderDark = Color(0xFF36343A)